name: EcoEnchants
version: ${projectVersion}
main: com.willfp.ecoenchants.EcoEnchantsPlugin
api-version: 1.17
authors: [ Auxilor ]
website: willfp.com
load: STARTUP
depend:
  - eco
  - ProtocolLib
softdepend:
  - Vault
  - AureliumSkills
  - PlayerPoints
  - Jobs
  - TMMobcoins
  - Reforges
  - EcoBosses
  - Talismans
  - EcoArmor
  - EcoItems
  - EcoSkills
  - Boosters

commands:
  ecoenchants:
    description: Base Command
    permission: ecoenchants.command.ecoenchants
  enchantinfo:
    description: Show info about an enchant
    permission: ecoenchants.command.enchantinfo

permissions:
  ecoenchants.*:
    description: All ecoenchants permissions
    default: op
    children:
      ecoenchants.command.*: true
      ecoenchants.anvil.*: true
      ecoenchants.fromtable.*: true
  ecoenchants.command.*:
    description: All commands
    default: op
    children:
      ecoenchants.command.reload: true
      ecoenchants.command.ecoenchants: true
      ecoenchants.command.toggledescriptions: true
      ecoenchants.command.giverandombook: true
      ecoenchants.command.enchantinfo: true
      ecoenchants.command.gui: true
      ecoenchants.command.import: true
      ecoenchants.command.export: true
  ecoenchants.anvil.*:
    description: All anvil perks
    default: op
    children:
      ecoenchants.anvil.color: true

  ecoenchants.anvil.color:
    description: Allows using color codes in anvils
    default: op
  ecoenchants.command.reload:
    description: Allows reloading the config
    default: op
  ecoenchants.command.giverandombook:
    description: Allows giving random books
    default: op
  ecoenchants.command.ecoenchants:
    description: Allows the use of /ecoenchants.
    default: true
  ecoenchants.command.toggledescriptions:
    description: Allows the use of /ecoenchants toggledescriptions.
    default: true
  ecoenchants.command.enchantinfo:
    description: Allows the use of /enchantinfo.
    default: true
  ecoenchants.command.gui:
    description: Allows the use of /ecoenchants gui.
    default: true
  ecoenchants.command.import:
    description: Allows the use of /ecoenchants import.
    default: op
  ecoenchants.command.export:
    description: Allows the use of /ecoenchants export.
    default: op